version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: irechargedb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '7001:7001'
    depends_on:
      - mysql
      - redis
    environment:
      HOST: localhost
      DB_NAME: irechargedb
      DB_USER: root
      DB_PASS: password
      PORT: 7001
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: irechargedb
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  mysql-data:
