version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - irecharge-network

  postgres:
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '5432:5432'
    networks:
      - irecharge-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    ports:
      - '7001:7001'
    networks:
      - irecharge-network
    environment:
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      PORT: 7001
      REDIS_HOST: redis
      jwtkey: ${jwtkey}
    depends_on:
      - postgres
      - redis

networks:
  irecharge-network:
    driver: bridge
