version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - irecharge-network

  postgres:
    image: postgres:latest
    volumes:
      - ./pgdata:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: irechargedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    networks:
      - irecharge-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    ports:
      - '7001:7001'
    networks:
      - irecharge-network
    environment:
      DB_HOST: postgres
      DB_NAME: irechargedb
      DB_USER: postgres
      DB_PASS: password
      PORT: 7001
      REDIS_HOST: redis
      jwtkey: irecharge-df354a95-d41b-d6a8-9eff-e13613a1f7f4
    depends_on:
      - postgres
      - redis

networks:
  irecharge-network:
    driver: bridge
